(function(){"use strict";
var profile={},ctx=null,lastFit=null;
function $(id){return document.getElementById(id)}
function toast(t){var e=$("toast");e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1900)}
function uid(){return "resume_"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
var STOP=new Set("the and for with you your our are from this that will have has into about role team work working skills skill experience program graduate position opportunity responsibilities requirements required ability strong using use through across who what when where how their they them its but not all can also more other including within we us to of in on at as by be is or an a".split(" "));
function keywords(text,limit){var f={},xs=String(text||"").toLowerCase().match(/[a-z][a-z0-9+#.-]{2,}/g)||[];xs.forEach(w=>{w=w.replace(/^[^a-z0-9]+|[^a-z0-9+#.-]+$/g,"");if(!w||STOP.has(w)||/^\d+$/.test(w))return;f[w]=(f[w]||0)+1});return Object.keys(f).sort((a,b)=>f[b]-f[a]||b.length-a.length).slice(0,limit||45)}
function fitScore(text,jd){var ks=keywords(jd,45);if(!ks.length)return{score:0,hits:0,total:0,keywords:[]};var low=String(text||"").toLowerCase(),hit=ks.filter(k=>low.includes(k));return{score:Math.min(99,Math.round(100*hit.length/ks.length)),hits:hit.length,total:ks.length,keywords:hit}}
async function load(){var o=await chrome.storage.local.get(["profile","gfResumeContext"]);profile=o.profile||{};profile.resumeVersions=profile.resumeVersions||[];ctx=o.gfResumeContext||{};var r=ctx.role||{};$("company").value=r.company||"";$("role").value=r.title||"";$("jobDescription").value=r.description||"";updateHeading();renderVersions();var p=await GFCloud.plan();$("planBadge").textContent=(p.name||p.id)+(p.price?" · "+p.price:"");await refreshQuota()}
function updateHeading(){$("roleHeading").textContent=[$("role").value.trim(),$("company").value.trim()].filter(Boolean).join(" · ")||"Current application"}
$("company").oninput=updateHeading;$("role").oninput=updateHeading;
async function detectRole(){var tab=null;if(ctx&&ctx.sourceTabId){try{tab=await chrome.tabs.get(ctx.sourceTabId)}catch(e){}}if(!tab){var tabs=await chrome.tabs.query({active:true,currentWindow:true});tab=tabs[0]}if(!tab||String(tab.url||"").startsWith("chrome-extension://")){toast("Open the application tab, then return here");return}try{var rsAll=await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},files:["rules.js","content.js"]});var ids=rsAll.map(x=>x.frameId),best=null;for(var i=0;i<ids.length;i++){try{var rs=await chrome.tabs.sendMessage(tab.id,{type:"GF_DETECT_ROLE"},{frameId:ids[i]});if(rs&&rs.role&&(rs.role.company||rs.role.title||rs.role.description)){best=Object.assign({},best||{},rs.role);if(rs.role.description&&(!best.description||rs.role.description.length>best.description.length))best.description=rs.role.description}}catch(e){}}if(best){$("company").value=best.company||$("company").value;$("role").value=best.title||$("role").value;$("jobDescription").value=best.description||$("jobDescription").value;ctx.role=Object.assign({},ctx.role||{},best);await chrome.storage.local.set({gfResumeContext:ctx});updateHeading();toast("Role context refreshed")}}catch(e){toast("Could not read that tab")}}
$("refreshRole").onclick=detectRole;
async function requireAI(featureLabel){var g=await GFCloud.canUseAI();if(!g.allowed){toast(featureLabel+" needs GradFill Pro or a Season Pass — autofill and the tracker stay free either way.");$("detailsBtn").click();return false}return true}
async function refreshQuota(){var u=await GFCloud.usage();if(u&&u.resumeTailors)$("quotaHint").textContent="Resume tailors this month: "+u.resumeTailors.used+" / "+(u.resumeTailors.limit>=9999?"∞":u.resumeTailors.limit)+" · Cover letters this month: "+(u.coverLetters?u.coverLetters.used+" / "+(u.coverLetters.limit>=9999?"∞":u.coverLetters.limit):"—")}
$("tailor").onclick=async function(){var btn=this,jd=$("jobDescription").value.trim();if(!jd){toast("Add the job description first");return}if(!await requireAI("Resume tailoring"))return;btn.disabled=true;btn.textContent="Tailoring…";try{var role={company:$("company").value.trim(),title:$("role").value.trim(),description:jd};var res=await GFCloud.aiResumeTailor({profile:GFCloud.safeProfileForAI(profile),role:role,jobDescription:jd});$("result").value=res.content||res.resume||"";$("sourceBadge").textContent=res.demo?"Offline demo — heuristic":"AI draft — review required";$("sourceBadge").style.borderColor=res.demo?"":"#4c4f9b";var m=res.matchedSkills||[],k=res.keywords||[];$("matchedCount").textContent=m.length;$("keywordCount").textContent=k.length;$("metrics").hidden=false;lastFit=fitScore($("result").value,jd);if(lastFit.total)$("sourceBadge").textContent+=(" · "+lastFit.score+"% keyword fit");if(!$("versionName").value)$("versionName").value=[role.title,role.company].filter(Boolean).join(" · ");await refreshQuota()}catch(e){toast(e.code==="paywall"||e.code==="quota"?(e.message||"Upgrade to tailor with AI"):(e.message||"Could not tailor resume"))}finally{btn.disabled=false;btn.textContent="Tailor with AI"}};
$("coverLetter").onclick=async function(){var btn=this,jd=$("jobDescription").value.trim();if(!jd){toast("Add the job description first");return}if(!await requireAI("Cover letter generation"))return;btn.disabled=true;btn.textContent="Writing…";try{var role={company:$("company").value.trim(),title:$("role").value.trim(),description:jd};var res=await GFCloud.aiCoverLetter({profile:GFCloud.safeProfileForAI(profile),role:role,jobDescription:jd});$("coverResult").value=res.content||res.letter||"";$("coverSourceBadge").textContent=res.demo?"Offline demo — heuristic":"AI draft — review required";$("coverSourceBadge").hidden=false;await refreshQuota()}catch(e){toast(e.code==="paywall"||e.code==="quota"?(e.message||"Upgrade to generate a cover letter"):(e.message||"Could not generate cover letter"))}finally{btn.disabled=false;btn.textContent="Generate with AI"}};
$("copyCover").onclick=async()=>{try{await navigator.clipboard.writeText($("coverResult").value);toast("Copied")}catch(e){toast("Copy failed — select the text manually")}};
async function saveProfile(){await chrome.storage.local.set({profile});try{await GFCloud.syncProfile(profile);await GFCloud.syncTracker(profile.applications||[])}catch(e){}}
async function propagateResumeToSession(name){if(!ctx||!ctx.sourceTabId)return;var o=await chrome.storage.local.get("gfApplicationSessions"),map=o.gfApplicationSessions||{},s=map[String(ctx.sourceTabId)];if(!s)return;if(ctx.sessionId&&s.id!==ctx.sessionId)return;s.resumeUsed=name;s.updatedAt=new Date().toISOString();map[String(ctx.sourceTabId)]=s;await chrome.storage.local.set({gfApplicationSessions:map})}
$("saveVersion").onclick=async function(){var content=$("result").value.trim(),name=$("versionName").value.trim();if(!content||!name){toast("Generate/edit a resume and give the version a name");return}var jd=$("jobDescription").value.trim(),fit=fitScore(content,jd),v={id:uid(),name,company:$("company").value.trim(),role:$("role").value.trim(),createdAt:new Date().toISOString(),content,jobId:ctx&&ctx.jobId||"",matchScore:fit.score,matchedKeywords:fit.keywords};profile.resumeVersions.unshift(v);if(v.jobId){var a=(profile.applications||[]).find(x=>x.id===v.jobId);if(a){a.resumeUsed=name;a.resumeMatchScore=fit.score}}await propagateResumeToSession(name);await saveProfile();renderVersions();toast("Resume version saved and linked to this application")};
function renderVersions(){var root=$("versions");root.innerHTML="";if(!profile.resumeVersions.length){root.textContent="No saved tailored versions yet.";return}profile.resumeVersions.slice(0,12).forEach(v=>{var row=document.createElement("div");row.className="version";var d=document.createElement("div");d.innerHTML="<p></p><small></small>";d.querySelector("p").textContent=v.name;var bits=[v.role,v.company,new Date(v.createdAt).toLocaleDateString()];if(v.matchScore!=null)bits.push(v.matchScore+"% keyword fit");d.querySelector("small").textContent=bits.filter(Boolean).join(" · ");var b=document.createElement("button");b.className="ghost";b.textContent="Load";b.onclick=()=>{$("result").value=v.content||"";$("versionName").value=v.name||"";$("company").value=v.company||"";$("role").value=v.role||"";lastFit={score:v.matchScore||0};updateHeading()};row.append(d,b);root.appendChild(row)})}
$("copy").onclick=async()=>{try{await navigator.clipboard.writeText($("result").value);toast("Copied")}catch(e){toast("Copy failed — select the text manually")}};
$("download").onclick=()=>{var text=$("result").value;if(!text){toast("Nothing to download");return}var u=URL.createObjectURL(new Blob([text],{type:"text/plain"}));var a=document.createElement("a");a.href=u;a.download=($("versionName").value.trim()||"gradfill-tailored-resume").replace(/[^a-z0-9_-]+/gi,"-")+".txt";a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)};
$("print").onclick=()=>window.print();$("trackerBtn").onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL("tracker.html")});$("detailsBtn").onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL("setup.html")});load();
})();
