(function(){"use strict";
var STATUSES=["Saved","Applying","Applied","Assessment","Interview","Offer","Rejected","Withdrawn"], profile={};
function $(id){return document.getElementById(id)} function uid(){return "job_"+Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function toast(t){var e=$("toast");e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1800)}
function esc(s){return String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
async function save(){await chrome.storage.local.set({profile});try{await GFCloud.syncTracker(profile.applications||[])}catch(e){}}
function ensure(){profile.applications=profile.applications||[];profile.applications.forEach(a=>{if(!a.id)a.id=uid();if(!a.status)a.status="Applied"});}
function filtered(){var q=$("search").value.trim().toLowerCase(), st=$("statusFilter").value;return (profile.applications||[]).filter(a=>{if(st&&a.status!==st)return false;if(!q)return true;return [a.company,a.role,a.location,a.keySkills,a.notes,a.resumeUsed].some(x=>String(x||"").toLowerCase().includes(q))})}
function card(a){var d=document.createElement("article");d.className="card";d.dataset.id=a.id;var chips=[];if(a.location)chips.push('<span class="chip">'+esc(a.location)+'</span>');if(a.resumeUsed)chips.push('<span class="chip">Resume: '+esc(a.resumeUsed)+'</span>');if(a.pagesFilled)chips.push('<span class="chip">'+esc(a.pagesFilled)+' page'+(Number(a.pagesFilled)===1?'':'s')+'</span>');if(a.dateApplied||a.date)chips.push('<span class="chip">Applied '+esc(a.dateApplied||a.date)+'</span>');d.innerHTML='<p class="role">'+esc(a.role||"Untitled role")+'</p><p class="company">'+esc(a.company||"Unknown company")+'</p><div class="meta">'+chips.join("")+'</div>'+(a.keySkills?'<p class="note"><strong>Matched skills:</strong> '+esc(a.keySkills)+'</p>':'')+(a.notes?'<p class="note">'+esc(a.notes)+'</p>':"");d.onclick=()=>openEdit(a.id);return d}
function render(){var arr=filtered(), b=$("board");b.innerHTML="";$("count").textContent=arr.length+" role"+(arr.length===1?"":"s");STATUSES.forEach(st=>{var col=document.createElement("section");col.className="column";var xs=arr.filter(a=>(a.status||"Applied")===st);col.innerHTML='<div class="column-head">'+esc(st)+' <span>'+xs.length+'</span></div>';if(xs.length)xs.forEach(a=>col.appendChild(card(a)));else{var e=document.createElement("div");e.className="empty";e.textContent="No roles";col.appendChild(e)}b.appendChild(col)})}
function populateSelects(){STATUSES.forEach(st=>{$("statusFilter").insertAdjacentHTML("beforeend",'<option>'+st+'</option>');$("jobStatus").insertAdjacentHTML("beforeend",'<option>'+st+'</option>')})}
var F={status:"jobStatus",company:"jobCompany",role:"jobRole",location:"jobLocation",employmentType:"jobType",closes:"jobCloses",dateApplied:"jobApplied",source:"jobSource",link:"jobLink",keySkills:"jobSkills",resumeUsed:"jobResume",notes:"jobNotes",jobDescription:"jobDescription"};
function openEdit(id){var a=(profile.applications||[]).find(x=>x.id===id)||{id:uid(),status:"Saved"};$("jobId").value=a.id;Object.keys(F).forEach(k=>$(F[k]).value=a[k]||((k==="dateApplied"&&a.date)||""));$("editTitle").textContent=a.role||"New role";$("deleteBtn").hidden=!(profile.applications||[]).some(x=>x.id===a.id);$("editor").showModal()}
async function commit(){var id=$("jobId").value||uid(), a=(profile.applications||[]).find(x=>x.id===id);if(!a){a={id};profile.applications.push(a)}Object.keys(F).forEach(k=>a[k]=$(F[k]).value.trim());a.date=a.dateApplied||a.date||"";if(!a.dateSaved)a.dateSaved=new Date().toISOString();await save();render();toast("Tracker updated")}
$("editForm").addEventListener("submit",async e=>{e.preventDefault();await commit();$("editor").close()});
$("addBtn").onclick=()=>openEdit(null);$("search").oninput=render;$("statusFilter").onchange=render;
$("deleteBtn").onclick=async()=>{var id=$("jobId").value;if(!confirm("Delete this tracker entry?"))return;profile.applications=profile.applications.filter(x=>x.id!==id);await save();$("editor").close();render();toast("Deleted")};
$("tailorBtn").onclick=async()=>{await commit();var a=profile.applications.find(x=>x.id===$("jobId").value);await chrome.storage.local.set({gfResumeContext:{jobId:a.id,role:{company:a.company||"",title:a.role||"",location:a.location||"",employmentType:a.employmentType||"",closes:a.closes||"",description:a.jobDescription||""}}});chrome.tabs.create({url:chrome.runtime.getURL("resume.html")})};
$("exportBtn").onclick=()=>{var cols=["status","company","role","location","dateApplied","link","keySkills","resumeUsed","notes"];var q=v=>'"'+String(v||"").replace(/"/g,'""')+'"';var csv=[cols.join(",")].concat((profile.applications||[]).map(a=>cols.map(k=>q(a[k]||((k==="dateApplied"&&a.date)||""))).join(","))).join("\r\n");var u=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));var a=document.createElement("a");a.href=u;a.download="gradfill-job-tracker.csv";a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)};
$("syncBtn").onclick=async()=>{try{var s=await GFCloud.getSettings();if(s.mode==="demo"){toast("Offline demo: tracker is local only");return}var a=await GFCloud.getAccount();if(!a||!a.token){toast("Sign in from Details first");return}await GFCloud.syncTracker(profile.applications||[]);var remote=await GFCloud.pullTracker();if(remote&&remote.length){profile.applications=remote;ensure();await chrome.storage.local.set({profile});render()}toast("Tracker synced")}catch(e){toast(e.message||"Sync failed")}};
(async function(){populateSelects();var o=await chrome.storage.local.get("profile");profile=o.profile||{};ensure();await chrome.storage.local.set({profile});var p=await GFCloud.plan();$("planBadge").textContent=(p.name||p.id)+(p.price?" · "+p.price:"");render()})();
})();
